config/routes.rb
Fetedelamusique::Application.routes.draw do
  devise_for :users

  resources :concerts
  resources :bands

  namespace :api do
    resources :concerts, :guides
  end

  root :to => 'concerts#index'

end

app/models/concert.rb
class Concert
  include Mongoid::Document
  include Mongoid::Timestamps

  field :artist, type: String
  field :genre, type: String
  field :time_start, type: Time
  field :time_end, type: Time
  field :is_official, type: Boolean
  field :description, type: String
  field :venue, type: String
  field :reason, type: String

  field :coordinates, type: Array

  index({ coordinates: "2d" }, { min: -200, max: 200 })

  belongs_to :user
  belongs_to :guide
end

app/models/guide.rb
class Guide
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :way_name, type: String
  field :way_desc, type: String

  has_one :user
  has_many :concert_steps, class_name: "Concert"
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  has_many :concerts
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
end

app/controllers/api/concerts_controller.rb
class Api::ConcertsController < Api::ApiController
  def index
    @concerts = Concert.all
  end
end

app/controllers/api/guides_controller.rb
class Api::GuidesController < Api::ApiController
  def index
    @guides = Guide.all
  end

  def show
    @guide = Guide.find params[:id]
  end

  def create
    @guide = Guide.new params[:guide]
    ids = Array.new
    binding.pry
    params[:guide]["concert_steps"].each do |c|
      concert = Concert.create c
      ids << concert
    end
    @guide.concert_steps = ids

    if @guide.save
      render 'api/guides/show', status: :created
    else
      render text: {errors: @guide.errors}.to_json, status: :unprocessable_entity
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout :layout_by_resource

  respond_to :html

protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

  before_filter :authenticate_user!, except: %w(index)

  def index
    @concerts = Concert.all
  end

  def new
    @concert = Concert.new
  end

  def create
    @concert = Concert.create params[:concert]
    respond_with @concert, location: concerts_path   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/concerts/_form.html.haml
= simple_form_for(@concert, :html => {:class => 'form-horizontal' }) do |f|
  = f.input :artist
  = f.input :genre
  = f.input :description
  = f.input :venue
  = f.input :time_start
  = f.input :time_end
  = f.button :submit, "Envoyer", :class => "btn btn-large btn-primary"

app/views/concerts/index.html.haml
%ul
  - @concerts.each do |c|
    %li
      = "#{c.artist} @ #{c.venue}"
      %span.date
        = "#{c.time_start.to_i} → #{c.time_end.to_i}"

app/views/concerts/new.html.haml
%section
  .container
    .row
      .span12
        = render :partial => "form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "Enrichment"
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Oswald:400,300,700'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic'
    = stylesheet_link_tag "application"
    = csrf_meta_tags

  %body
    =# render "shared/nav" if user_signed_in?
    %section
      .container
        .row
          .span12
            %h1
              FÊTE
              %span DE LA
              MUSIQUE
        .row
          = link_to "Je veux ajouter un nouveau concert !", new_concert_path, class: "new-group"
    = yield
    = javascript_include_tag "application"

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title= "Fête de la Musique 2013 à Strasbourg"
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Oswald:400,300,700'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic'
    = stylesheet_link_tag "application"
    = csrf_meta_tags

  %body.narrow
    .container.content.narrow
      = yield
    = javascript_include_tag "application"